"use strict";
const $=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
let meta,shown,follow=true,outcome=false,polling=false;
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data}
function safe(fn){return async(...args)=>{try{$('error').hidden=true;await fn(...args)}catch(e){$('error').hidden=false;$('error').textContent=e.message}}}
function frame(){if(!shown)return;$('frame').src=outcome&&shown.after_frame?shown.after_frame:shown.frame;$('frameToggle').disabled=!shown.after_frame;$('frameToggle').textContent=!shown.after_frame?(shown.sequence?'Terminal input / no next frame':'Decision input'):outcome?'Show decision input':'Show action outcome'}
function trace(){const svg=$('trace');svg.replaceChildren();const rows=shown?.trace||[],kind=$('population').value;if(!rows.length)return;const vals=rows.map(r=>r.values[kind]),min=Math.min(0,...vals),max=Math.max(0,...vals),range=Math.max(max-min,1e-9),end=rows.at(-1).ms,ns='http://www.w3.org/2000/svg';const add=(tag,attrs,text)=>{const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;svg.append(n)};add('text',{x:10,y:16,fill:'#637568','font-size':10},`${kind} / dimensionless state / ${max.toExponential(2)}`);add('line',{x1:45,y1:130-(0-min)/range*100,x2:580,y2:130-(0-min)/range*100,stroke:'#c7d1c0'});add('polyline',{points:rows.map((r,i)=>`${45+535*r.ms/end},${130-(vals[i]-min)/range*100}`).join(' '),fill:'none',stroke:'#a36732','stroke-width':2});add('text',{x:45,y:154,fill:'#637568','font-size':10},`0 → ${end.toFixed(1)} ms / min ${min.toExponential(2)}`)}
function paint(s){shown=s;frame();$('decision').textContent='DECISION '+String(s.sequence).padStart(3,'0');$('action').textContent=s.action;
 $('actions').replaceChildren(...meta.actions.map((name,i)=>{const n=el('div');n.className='action'+(name===s.action?' selected':'');n.append(el('span',name.replace('MOVE_','')),el('span',(s.probabilities[i]*100).toFixed(1)+'%'));const bar=el('div'),fill=el('i');bar.className='bar';fill.style.width=(s.probabilities[i]*100)+'%';bar.append(fill);n.append(bar);return n}));
 $('selectionNote').textContent=s.sequence?(s.learning_at_decision?'Sampled from the T4/T5 neural policy; reward learning enabled.':'Highest-probability T4/T5 neural action; weights frozen.'):'No action yet. The first step processes the initial image.';
 $('cells').replaceChildren(...(s.terms?.cells||[]).map(c=>{const row=el('tr'),name=el('td'),button=el('button',c.cell_type);button.onclick=safe(()=>selectIntegratedCell(c.root_id));name.append(button,el('small',c.root_id));row.append(name,...[c.state,c.weight,c.activation,c.contribution].map(v=>el('td',v.toExponential(3))));return row}));
 $('logit').textContent=s.terms?`Selected-action logit ${s.terms.logit.toFixed(5)} = all neural products ${s.terms.all_neural_terms.toFixed(5)} + bias ${s.terms.bias.toFixed(5)}. Products outside this table: ${s.terms.other_terms.toFixed(5)}.`:'Waiting for the first decision.';
 $('reward').textContent=s.sequence?(s.reward>0?'+':'')+s.reward:'—';$('return').textContent=`Episode return ${s.return} / kills ${s.kills}`;
 const f=s.feedback;$('delta').textContent=f?f.weight_delta_l2.toExponential(3):'Frozen';$('updates').textContent=f?`${f.updates} reward updates this episode`:'No optimizer update at this decision';$('probability').textContent=f?`${(100*f.action_probability_before).toFixed(2)}% → ${(100*f.action_probability_after).toFixed(2)}%`:'—';
 $('feedbackNote').textContent=f?'Reward changed the live decoder after this action. The next decision uses its new weights. Biological graph gains stay fixed during live play. The saved experiment checkpoint remains intact.':'Game reward is recorded. Enable Learn from reward while paused to apply stochastic policy updates.';
 $('timing').textContent=s.sequence?`Encoder ${s.encoding_ms.toFixed(1)} ms / decision computation ${s.wall_ms.toFixed(1)} ms (excludes archive write). Neural clock ${s.neural_clock_ms.toFixed(1)} ms. State updates use a fixed 114.3 ms response window.`:'';
 $('runPath').textContent=s.run;trace();history(s.latest_sequence);paintIntegrated(s)
}
function history(count){$('history').replaceChildren(...Array.from({length:count+1},(_,i)=>{const b=el('button',String(i).padStart(2,'0'));b.setAttribute('aria-pressed',String(i===shown?.sequence));b.onclick=safe(async()=>{await api('/api/control',{command:'pause'});follow=false;paint(await api('/api/state?sequence='+i))});return b}))}
for(const command of ['run','pause','step','stop'])$(command).onclick=safe(async()=>{if(command==='run'||command==='step')follow=true;await api('/api/control',{command});await poll()});
$('learning').onchange=safe(async()=>{await api('/api/learning',{enabled:$('learning').checked});await poll()});
$('newRun').onclick=safe(async()=>{await api('/api/new-run',{seed:Number($('seed').value)});follow=true;shown=null;await poll()});
$('follow').onclick=safe(async()=>{follow=true;shown=null;await poll()});$('frameToggle').onclick=()=>{outcome=!outcome;frame()};$('population').onchange=trace;
async function poll(){if(polling)return;polling=true;try{const s=await api('/api/state');$('connection').textContent=s.busy?'COMPUTING':'CONNECTED';$('phase').textContent=s.phase==='ready'?(s.busy?'Computing':s.paused?'Paused':'Running'):s.phase;for(const name of ['run','step'])$(name).disabled=s.busy||s.teacher_busy||s.phase!=='ready';$('learning').disabled=s.busy||s.teacher_busy||!s.paused;$('learning').checked=s.learning;$('newRun').disabled=s.busy||s.teacher_busy||!s.paused||teacherRequest;$('compareTeacher').disabled=s.busy||s.teacher_busy||!s.paused||teacherRequest;if(s.error)throw Error(s.error);if(follow&&(!shown||s.sequence!==shown.sequence||s.run!==shown.run))paint(s);else history(s.latest_sequence)}catch(e){$('error').hidden=false;$('error').textContent=e.message}finally{polling=false}}
safe(async()=>{meta=await api('/api/meta');$('neuronCount').textContent=meta.neurons.toLocaleString();$('readoutCount').textContent=meta.readout_cells;const b=$('benchmark');b.replaceChildren(...Object.entries(meta.benchmark).map(([name,r])=>el('div',`${name.replaceAll('_',' ')}: ${r.kills}/${r.episodes} kills; mean return ${r.mean_return.toFixed(1)}`)));await startIntegrated();await poll();setInterval(poll,350)})();
